version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra-net

  spark:
    image: bitnami/spark:latest
    container_name: spark-node
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "4040:4040"
    networks:
      - cassandra-net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-node
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - cassandra-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-node
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - cassandra-net 

networks:
  cassandra-net:
