version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra
    ports:
      - "9042:9042"
    networks:
      - app-net

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master-node
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "4040:4040"
    networks:
      - app-net

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark-master-node:7077
    networks:
      - app-net

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark-master-node:7077
    networks:
      - app-net

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark-master-node:7077
    networks:
      - app-net
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper-node
    networks:
      - app-net
      
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    container_name: kafka-node
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-net

  python-app:
    build:
      context: .  # Le contexte est le répertoire courant où se trouve votre Dockerfile
      dockerfile: Dockerfile  # Spécifiez le nom de votre Dockerfile s'il est différent de 'Dockerfile'
    container_name: python-app
    networks:
      - app-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-net: