version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra-net

  spark:
    image: bitnami/spark:latest
    container_name: spark-node
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "4040:4040"
    networks:
      - cassandra-net

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper-node
    networks:
      - cassandra-net
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-node
    hostname : kafka-node
    networks:
      - cassandra-net
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-node:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-node:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  python-app:
    build:
      context: .  # Le contexte est le répertoire courant où se trouve votre Dockerfile
      dockerfile: Dockerfile  # Spécifiez le nom de votre Dockerfile s'il est différent de 'Dockerfile'
    container_name: python-app
    depends_on:
      - kafka  # Si votre script Python dépend de Kafka
    networks:
      - cassandra-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  cassandra-net:
